services:
  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - redis
      - database
    environment:
      - DATABASE_HOST=database
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=nestjs
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev

  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'

  database:
    image: 'postgres:13'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nestjs
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: